config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :users, controllers: {sessions: "users/sessions"},
      path: "", path_names: {sign_in: "login",
                             sign_out: "logout", edit: "edit", sign_up: "signup"}
    namespace :admin do
      root "home#index"
    end
    resources :books do
      resources :markers, only: %i(create destroy)
      resources :reviews
    end
    resources :purchase_requests, only: %i(index destroy)
    resources :favorites, only: %i(index destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_profile
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :markers
  has_many :reviews, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :activities

  devise :database_authenticatable, :registerable, :confirmable, :lockable,
    :recoverable, :rememberable, :validatable
  accepts_nested_attributes_for :user_profile

  def recent_activities limit
    activities.order("created_at DESC").limit limit
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    resource = get_user

    return handle_failure :not_found_in_database unless resource

    return handle_failure :invalid unless
      resource.valid_password? params[:user][:password]

    return handle_failure :unconfirmed unless
      resource.active_for_authentication?

    resource = warden.authenticate!(auth_options) if
      params[:user][:remember_me] == Settings.remember
    handle_success resource
  end

  private

  def get_user
    User.find_for_database_authentication email: params[:user][:email]
  end

  def handle_failure fail_value
    set_flash_message :danger, fail_value
    respond_to do |format|
      format.js
    end
  end

  def handle_success resource
    set_flash_message :primary, :signed_in
    sign_in :user, resource
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
        count: resource.errors.count,
          resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != "sessions" %>
  <%= link_to t(".login"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to t(".signup"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t(".signin_with"), omniauth_authorize_path(resource_name, provider) %>
    <br />
  <% end %>
<% end %>