config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :users, controllers: {sessions: "users/sessions"},
      path: "", path_names: {sign_in: "login",
                             sign_out: "logout", edit: "edit", sign_up: "signup"}
    namespace :admin do
      root "home#index"
    end
    resources :books do
      resources :markers, only: %i(create destroy)
      resources :reviews
    end
    resources :purchase_requests, only: %i(index destroy)
    resources :favorites, only: %i(index destroy)
  end
end

app/models/marker.rb
class Marker < ApplicationRecord
  AUTHORIZE_USER = %w(create delete).freeze

  enum status: {favorite: 1, readed: 2, reading: 3, purchase_request: 4,
                rate_and_review: 5}

  belongs_to :user
  belongs_to :book
  has_one :activity, as: :activitable, dependent: :destroy

  validates :status, uniqueness: {scope: %i(user_id book_id)}

  after_create :create_activities

  scope :created_at_desc, ->{order created_at: :desc}

  private

  def create_activities
    create_activity user: user
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  authorize_resource
  before_action :get_book
  before_action :get_marker, only: %i(destroy)

  def create
    @marker = current_user.markers.new book_id: params[:book_id],
      status: params[:status]
    respond_to do |format|
      if @marker.save
        format.js
      else
        format.js{redirect_to books_path}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @marker.destroy
        format.js
      else
        format.js{redirect_to books_path}
      end
    end
  end

  private

  def get_book
    return if @book = Book.find_by(id: params[:book_id])
    flash[:danger] = t ".book_not_found"
    redirect_back fallback_location: books_path
  end

  def get_marker
    return if @marker = current_user.markers.find_by(book_id: params[:book_id],
      id: params[:id])
    flash[:danger] = t ".marker_not_found"
    redirect_back fallback_location: books_path
  end
end

app/helpers/markers_helper.rb
module MarkersHelper
  def marker_form book_id, status, user
    return unless user.instance_of? User
    if @marker = user.markers.find_by(book_id: book_id, status: status)
      render "markers/form/cancel_#{@marker.status}", object: @marker
    else
      render "markers/form/#{status}"
    end
  end

  def status_marker marker
    return unless marker.instance_of? Marker
    Marker.human_enum_name :status, :"#{marker.status}"
  end

  def check_favorite? book_id, user
    return true if user.markers.find_by(book_id: book_id, status: :favorite) &&
                   user.instance_of?(User)
  end
end

app/views/markers/form/_cancel_favorite.html.erb
<%= form_with url: book_marker_path(@book, @marker), method: :delete do |f| %>
  <%= image_tag "svg/no-favorite.svg", class: "icon-marker" %>
  <%= f.button t(".cancel_favorite"), class: "btn btn-secondary rounded" %>
<% end %>

app/views/markers/form/_cancel_purchase_request.html.erb
<%= form_with url: book_marker_path(@book, @marker), method: :delete do |f| %>
  <%= image_tag "svg/cancel-purchase-request.svg", class: "icon-marker" %>
  <%= f.button t(".cancel_purchase_request"),
    class: "btn btn-secondary rounded" %>
<% end %>

app/views/markers/form/_cancel_readed.html.erb
<%= form_with url: book_marker_path(@book, @marker), method: :delete do |f| %>
  <%= image_tag "svg/cancel-readed.svg", class: "icon-marker" %>
  <%= f.button t(".cancel_readed"), class: "btn btn-secondary rounded" %>
<% end %>

app/views/markers/form/_cancel_reading.html.erb
<%= form_with url: book_marker_path(@book, @marker), method: :delete do |f| %>
  <%= image_tag "svg/cancel-reading.svg", class: "icon-marker" %>
  <%= f.button t(".cancel_reading"), class: "btn btn-secondary rounded" %>
<% end %>

app/views/markers/form/_favorite.html.erb
<%= form_with url: book_markers_path(@book) do |f| %>
  <%= f.hidden_field :status, value: :favorite %>
  <%= image_tag "svg/favorite.svg", class: "icon-marker" %>
  <%= f.button t(".favorite"), class: "btn btn-primary rounded" %>
<% end %>

app/views/markers/form/_purchase_request.html.erb
<%= form_with url: book_markers_path(@book) do |f| %>
  <%= f.hidden_field :status, value: :purchase_request %>
  <%= image_tag "svg/purchase-request.svg", class: "icon-marker" %>
  <%= f.button t(".purchase_request"), class: "btn btn-primary rounded" %>
<% end %>

app/views/markers/form/_readed.html.erb
<%= form_with url: book_markers_path(@book) do |f| %>
  <%= f.hidden_field :status, value: :readed %>
  <%= image_tag "svg/readed.svg", class: "icon-marker" %>
  <%= f.button t(".readed"), class: "btn btn-primary rounded" %>
<% end %>

app/views/markers/form/_reading.html.erb
<%= form_with url: book_markers_path(@book) do |f| %>
  <%= f.hidden_field :status, value: :reading %>
  <%= image_tag "svg/reading.svg", class: "icon-marker" %>
  <%= f.button t(".reading"), class: "btn btn-primary rounded" %>
<% end %>