config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :users, controllers: {sessions: "users/sessions"},
      path: "", path_names: {sign_in: "login",
                             sign_out: "logout", edit: "edit", sign_up: "signup"}
    namespace :admin do
      root "home#index"
    end
    resources :books do
      resources :markers, only: %i(create destroy)
      resources :reviews
    end
    resources :purchase_requests, only: %i(index destroy)
    resources :favorites, only: %i(index destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-9">
            <h2 class="footer-heading mb-4">
              <%= t ".about_us" %>
            </h2>
            <p>
              <%= t ".introduce" %><br>
              <%= t ".address" %><br>
              <%= t ".telephone" %>
            </p>
          </div>
          <div class="col-md-3">
            <h2 class="footer-heading mb-4">
              <%= t ".follow_us" %>
            </h2>
            <a href="#" class="pl-0 pr-3">
              <span class="icon-facebook"></span>
            </a>
            <a href="#" class="pl-3 pr-3">
              <span class="icon-twitter"></span>
            </a>
            <a href="#" class="pl-3 pr-3">
              <span class="icon-instagram"></span>
            </a>
            <a href="#" class="pl-3 pr-3">
              <span class="icon-linkedin"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <%= form_with url: "#", local: true do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :book_name, class: "form-control border-secondary
              text-white bg-transparent", placeholder: t(".search_book") %>
            <div class="input-group-append">
              <%= f.button t(".search"), class: "btn btn-primary text-white" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row pt-3 mt-3 text-center">
      <div class="col-md-12">
        <div class="border-top pt-3">
          <p>
            <!-- Link back to Colorlib can't be removed.
              Template is licensed under CC BY 3.0. -->
            <%= t ".copyright1" %>
            <i class="icon-heart" aria-hidden="true"></i>
            <%= t ".copyright2" %>
            <%= link_to t(".colorlib"), "https://colorlib.com",
              target: "_blank" %>
            <!-- Link back to Colorlib can't be removed.
              Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,
  initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800"
  rel="stylesheet">
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload",
  defer: true %>
<%= javascript_include_tag "i18n" %>
<script>
  I18n.defaultLocale = "<%= I18n.default_locale %>"
  I18n.locale = "<%= I18n.locale || I18n.default_locale %>"
</script>
<% render "layouts/shim" %>

app/views/layouts/_header.html.erb
<div class="navbar-expand-sm fixed-top">
  <header class="site-navbar container py-0" role="banner">
    <div class="row align-items-center">
      <div class="col-6 col-xl-2">
        <h1 class="mb-0 site-logo">
          <%= link_to "#", class: "text-white mb-0" do %>
            <span class="flaticon-books"></span>
            <%= t ".title1" %>
            <span class="text-primary"><%= t ".title2" %></span>
          <% end %>
        </h1>
      </div>
      <div class="col-12 col-md-10 d-none d-xl-block">
        <nav class="site-navigation position-relative text-right"
          role="navigation">
          <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block">
            <li class="<%= "active" if request.original_url == root_url %>">
              <%= link_to t(".home"), root_path %>
            </li>
            <% if current_user %>
              <li class="has-children">
                <%= link_to t(".book"), books_path %>
                <% if current_user.admin? %>
                  <ul class="dropdown">
                    <li>
                      <%= link_to t(".create_book"), new_book_path %>
                    </li>
                  </ul>
                </li>
                <% else %>
                  <ul class="dropdown">
                    <li>
                      <%= link_to t(".favorite"), favorites_path %>
                    </li>
                    <li>
                      <%= link_to t(".reading"), "#" %>
                    </li>
                    <li>
                      <%= link_to t(".readed"), "#" %>
                    </li>
                  </ul>
                </li>
                <% end %>
            <% else %>
              <li>
                <%= link_to t(".book"), books_path %>
              </li>
            <% end %>
            <li>
              <%= link_to t(".request_book"), purchase_requests_path %>
            </li>
            <li>
              <%= link_to t(".contact"), "#" %>
            </li>
            <li class="has-children">
              <%= link_to t(".language") %>
              <ul class="dropdown">
                <li>
                  <%= link_to locale: "en" do %>
                    <%= image_tag "en.jpg", class: "image-language" %>
                    <%= t ".english" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to locale: "vi" do %>
                    <%= image_tag "vi.jpg", class: "image-language" %>
                    <%= t ".vietnamese" %>
                  <% end %>
                </li>
              </ul>
            </li>
            <span class="border-left pl-xl-2"></span>
            <% if user_signed_in? %>
              <li class="has-children">
                <%= link_to locale: "en" do %>
                  <%= image_tag "icon/user.png", class: "image-language" %>
                  <%= current_user.email %>
                <% end %>
                <ul class="dropdown">
                  <li>
                    <%= link_to admin_root_path do %>
                      <%= t ".personal_information"%>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <%= t ".change_password" %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <%= t ".sign_out" %>
                    <% end %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li class="ml-xl-3 login">
                <%= link_to "#", data: {toggle: "modal",
                  target: "#loginModal"} do%>
                  <%= t ".sign_in"%>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                  <%= t(".register") %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
      <div class="d-inline-block d-xl-none ml-auto py-3 col-6 text-right"
        id="bottom-header">
        <a href="#" class="site-menu-toggle js-menu-toggle text-white">
          <span class="icon-menu h3"></span>
        </a>
      </div>
    </div>
  </header>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="loginModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-primary">
          Sign in
        </h4>
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center">
          <div class="col-md-8" data-aos="fade">
            <%= form_for resource, :as => resource_name,
              url: session_path(resource_name), remote: true do |f| %>
              <div class="row form-group">
                <div class="col-md-12" id="alert-login">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <%= f.label :email, class: "text-black" %><br/>
                  <%= f.email_field :email, class: "form-control" %>
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <%= f.label :password, class: "text-black" %><br/>
                  <%= f.password_field :password, class: "form-control" %>
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me, class: "text-black" %>
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <%= f.submit "Log in",
                    class: "btn btn-primary py-2 px-4 text-white" %>
                </div>
              </div>
            <% end %>
            <%= render "users/shared/links" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_site_blocks.html.erb
<div class="site-blocks-cover overlay" id="bg-site-blocks" data-aos="fade"
  data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-12">
        <div class="row justify-content-center mb-4">
          <div class="col-md-8 text-center">
            <h1 class="" data-aos="fade-up">
              <%= t ".title" %>
            </h1>
            <p data-aos="fade-up" data-aos-delay="100">
              <%= t ".maxim" %>
            </p>
            <%= render "shared/flash" %>
          </div>
        </div>
        <div class="form-search-wrap" data-aos="fade-up" data-aos-delay="200">
          <%= form_with url: "#", local: true do |f| %>
            <div class="row align-items-center">
              <div class="col-lg-12 mb-4 mb-xl-0 col-xl-7">
                <%= f.text_field :content, class: "form-control rounded",
                  placeholder: t(".search_content") %>
              </div>
              <div class="col-lg-12 mb-4 mb-xl-0 col-xl-3">
                <div class="select-wrap">
                  <span class="icon">
                    <span class="icon-keyboard_arrow_down"></span>
                  </span>
                  <%= f.select :format, [],
                    {include_blank: t(".can_choose_format")},
                      class: "form-control rounded" %>
                </div>
              </div>
              <div class="col-lg-12 col-xl-2 ml-auto text-right">
                <%= f.submit t(".search"),
                  class: "btn btn-primary btn-block rounded"%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_statistical.html.erb
<div class="site-section bg-light">
  <div class="container">
    <div class="overlap-category mb-5">
      <div class="row align-items-stretch no-gutters">

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/users.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".users" %>
            </span>
            <span class="number">43,921</span>
          </span>
        </div>

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/books.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".books" %>
            </span>
            <span class="number">1000</span>
          </span>
        </div>

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/website.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".website" %>
            </span>
            <span class="number">200</span>
          </span>
        </div>

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/mobile.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".mobile" %>
            </span>
            <span class="number">500</span>
          </span>
        </div>

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/pc.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".desktop" %>
            </span>
            <span class="number">100</span>
          </span>
        </div>

        <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
          <span href="#" class="popular-category h-100">
            <span class="icon">
              <%= image_tag "svg/think.svg", class: "statistical" %>
            </span>
            <span class="caption mb-2 d-block">
              <%= t ".orther" %>
            </span>
            <span class="number">200</span>
          </span>
        </div>

      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <h2 class="h5 mb-4 text-black">
          <%= t ".highest_rated" %>
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12  block-13">
        <div class="owl-carousel nonloop-block-13">
          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_1.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_2.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_3.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_3.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_4.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_2.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

          <div class="d-block d-md-flex listing vertical">
            <%= link_to "#", class: "img d-block" do %>
              <%= image_tag "img_3.jpg" %>
            <% end %>
            <div class="lh-content">
              <span class="category">
                <%= t ".website" %>
              </span>
              <%= link_to "#", class: "bookmark" do %>
                <span class="icon-heart"></span>
              <% end %>
              <h3>
                <%= link_to t(".title_waiting"), "#" %>
              </h3>
              <address><%= t ".author_waiting" %></address>
              <p class="mb-0 rating">
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="icon-star text-warning"></span>
                <span class="review">(100 Reviews)</span>
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= favicon_link_tag yield :icon %>
    <%= render "layouts/head" %>
  </head>

  <body>
    <% if !user_signed_in? %>
      <%= render "layouts/login_modal" %>
    <% end %>
    <div class="site-wrap">
      <div class="site-mobile-menu">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>
      <%= render "layouts/header" %>
      <%= render "layouts/site_blocks" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>